pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm // Checks out the source code from the configured SCM
            }
        }

        // 'Setup' stage might not be necessary if you don't have a requirements.txt
        // and your application does not need any additional dependencies to be installed

        // If you have tests, you could include a 'Test' stage here
        // Make sure you have a testing framework installed and configured if you wish to run tests

        stage('Run') {
            steps {
                echo 'Starting Flask application...'
                // Starts Flask application
                // The 'sudo' command is not recommended in Jenkins pipelines for security reasons.
                // Instead, you should ensure Jenkins has the appropriate permissions, if possible.
                sh 'nohup python3 /var/lib/jenkins/workspace/python-test-project/python-simple-website-main/app.py > app.log 2>&1 &'
                // Note: Running Flask with `app.run()` is not recommended for production
            }
        }
    }

    post {
        always {
            echo 'Pipeline has finished executing.'
            // If you had a setup stage that needed cleanup, you would put the commands here
        }
    }
}
